[workspace]
members = [
    "two-sum",
    "add-two-numbers",
    "reverse-integer",
    "longest-substring-without-repeating-characters",
    "binary-tree-inorder-traversal",
    "same-tree",
    "symmetric-tree",
    "recover-binary-search-tree",
    "validate-binary-search-tree"
]