name: Deploy Doc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Version
      run: cargo -V
    - name: Run tests
      run: cargo test --verbose
