name: Deploy Doc

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Version
      run: cargo -V
    - name: GenDoc
      run: cargo doc
    - name: Look Result
      run: |
        ls target/doc
